# Generated by Django 4.2.10 on 2024-02-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DominantCliModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(editable=False, max_length=255)),
                ('exec_response', models.TextField(editable=False)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
