# Generated by Django 4.2.10 on 2024-02-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno_dominant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominantclimodel',
            name='command_name',
            field=models.CharField(max_length=255),
        ),
    ]
