# Generated by Django 4.2.10 on 2024-02-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno_dominant', '0002_alter_dominantclimodel_command_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominantclimodel',
            name='exec_response',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
