# Generated by Django 4.2.10 on 2024-02-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno_dominant', '0003_alter_dominantclimodel_exec_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominantclimodel',
            name='command_name',
            field=models.CharField(choices=[('command1', 'command1'), ('command2', 'command2'), ('command3', 'command3'), ('command4', 'command4'), ('command5', 'command5'), ('command6', 'command6'), ('command7', 'command7'), ('command8', 'command8'), ('command9', 'command9'), ('command10', 'command10'), ('command11', 'command11'), ('command12', 'command12')], max_length=255),
        ),
    ]
