# Generated by Django 4.2.10 on 2024-02-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techno_dominant', '0004_alter_dominantclimodel_command_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dominantclimodel',
            options={'ordering': ['-executed_at'], 'verbose_name_plural': 'Dominant Cli'},
        ),
    ]
